# Generated by Django 4.0.4 on 2022-05-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boiler_options_rename_topic_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='participant',
        ),
        migrations.DeleteModel(
            name='participant',
        ),
    ]
